# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/box21_api',
                'doc_host': 'https://ramonhollands.github.io',
                'git_url': 'https://github.com/ramonhollands/box21_api',
                'lib_path': 'box21_api'},
  'syms': {'box21_api.core': {'box21_api.core.foo': ('core.html#foo', 'box21_api/core.py')}}}