# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_asset.ipynb.

# %% auto 0
__all__ = ['Asset']

# %% ../02_asset.ipynb 3
class Asset:
    def __init__(self, 
                 deleted: str, 
                 id: int,
                 in_validation_set: bool,
                 liked: bool,
                 meta: str,
                 original_category: str,
                 path: str,
                 project_id: int,
                 unclear: bool,
                 validated: bool):
        self.deleted = deleted
        self.id = id
        self.in_validation_set = in_validation_set
        self.liked = liked
        self.meta = meta
        self.original_category = original_category
        self.path = path
        self.project_id = project_id
        self.unclear = unclear
        self.validated = validated

# %% ../02_asset.ipynb 4
class Asset(Asset):
    @classmethod
    def from_json(cls, json_dict):
        asset = cls(
            json_dict['deleted'],
            json_dict['id'],
            json_dict['in_validation_set'],
            json_dict['liked'],
            json_dict['meta'],
            json_dict['original_category'],
            json_dict['path'],
            json_dict['project_id'],
            json_dict['unclear'],
            json_dict['validated'],
        )
        return asset
