"""Box21 export"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../05_export.ipynb.

# %% auto 0
__all__ = ['export_asset', 'export_assets']

# %% ../05_export.ipynb 3
from typing import List
from .asset import Asset
from .box21_api import Box21Api

def export_asset(asset: Asset, api: Box21Api):
    annotations = api.get_annotations(asset.id)
    print('Would export asset')
    print('Annotations', annotations)

def export_assets(assets: List[Asset], api: Box21Api): 
    
    for asset in assets:
        export_asset(asset, api)
