# AUTOGENERATED! DO NOT EDIT! File to edit: ../05_job.ipynb.

# %% auto 0
__all__ = ['Job']

# %% ../05_job.ipynb 4
from abc import ABC, abstractmethod, abstractproperty

class Job(ABC):
    "Class that represents a Box21 Job"
    def __init__(self, 
                 id: int,
                 progress: int, #percentage
                 processed: int, #1=true, 0=false
                 description: int,
                 created_at: str,
                 parent_id: int,
                 project_id: int,
                 deleted_at: str,
                ):
        self.id = id
        self.progress = progress
        self.processed = processed
        self.description = description
        self.created_at = created_at
        self.parent_id = parent_id
        self.project_id = project_id
        self.deleted_at = deleted_at
        
    def __repr__(self):    
        return f"Job({self.id, self.created_at, self.description})"
